language: python

matrix:
  include:
    - python: "3.6"

cache:
  directories:
    - .pip_download_cache

env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"

before_script:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - python setup.py install_egg_info
  - pip install -e .
  - pip install .[tests]
  - pip install codecov

script:
  - coverage run -m py.test || exit 1

after_success:
  - codecov

notifications:
  email:
    - secops@netflix.com
