language: python
dist: bionic

python: 3.7

before_install:
  - sudo rm -f /etc/boto.cfg

cache:
  directories:
    - .pip_download_cache

env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"

install:
  - pip install tox-travis

matrix:
  include:
    - env:
    - env: TOXENV=linters

before_script:
  - pip install codecov

script:
  # - coverage run -m py.test || exit 1
  - tox

after_success:
  - codecov
